FROM node:22-alpine
ENV ROOT /usr/src/app
WORKDIR ${ROOT}
COPY frontend/package.json .
RUN npm install
COPY frontend/ .
COPY public ./public
COPY .docker.env .env

EXPOSE 3000
CMD ["node", "server.js"]
