[profile.dev]
debug = false
strip = "debuginfo"

[target.aarch64-linux-android]
rustflags = [
    "-C",
    "link-arg=-L",
    "-C",
    "link-arg=gen/android/app/src/main/jniLibs/arm64-v8a",
    "-C",
    "link-arg=-l:libffi.a",
    "-C",
    "link-arg=-Wl,--allow-shlib-undefined",
    "-C",
    "link-arg=-Wl,--unresolved-symbols=ignore-all",
]
